### https://rubyyagi.com/how-to-run-tests-in-parallel-in-github-actions/
### https://github.com/rubyyagi/bookmarker/blob/main/.github/workflows/test.yml

name: UnitTestMatrix
on: [push, pull_request]
jobs:
  maven-project-compile:
    runs-on: ubuntu-latest

    name: Java ${{ matrix.java }} compile
    strategy:
      fail-fast: false
      matrix:
        java: [ 
          11, 
          12, 
          13 
        ]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}
      - name: Compile the Project
        # working-directory: ./
        run: mvn -B compile


