### https://rubyyagi.com/how-to-run-tests-in-parallel-in-github-actions/
### https://github.com/rubyyagi/bookmarker/blob/main/.github/workflows/test.yml

name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
      ci_node_total: [2]
      ci_node_index: [0, 1]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Test echo 
        run: echo $HOSTNAME
