### https://rubyyagi.com/how-to-run-tests-in-parallel-in-github-actions/
### https://github.com/rubyyagi/bookmarker/blob/main/.github/workflows/test.yml

name: UnitTestMatrix
on: [push, pull_request]
jobs:
  maven-project-compile:
    timeout-minutes: 120 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands
        run: |
          ./mvnw compile 

  maven-project-test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands
        run: |
          ./mvnw test

  maven-project-package:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands
        run: |
          ./mvnw package

  maven-project-package:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands
        run: |
          ./mvnw package


  maven-project-verify:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands
        run: |
          ./mvnw verify


  maven-project-install:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands
        run: |
          ./mvnw install
